---
title: 2.6.3 exception对象
categories: 
  - 2 轻量级Java EE企业应用实战(第5版)
  - 第2章 JSP Servlet及相关技术详解
  - 2.6 JSP脚本中的9个内置对象
abbrlink: 4cf1bf4f
date: 2020-06-06 11:41:08
updated: 2022-04-03 01:21:16
---
# 2.6.3 exception对象
`exception`对象是`Throwable`的实例,代表`JSP`脚本中产生的错误和异常,是`JSP`页面异常机制的一部分。
在`JSP`脚本中无须处理异常,即使该异常是`checked`异常。事实上,`JSP`脚本包含的所有可能出现的异常都可交给错误处理页面处理。
看如图2.21所示的异常处理结构,这是典型的异常捕捉处理块。在`JSP`页面中,普通的`JSP`脚本只执行第一个部分——代码处理段,而异常处理页面负责第二个部分——异常处理段。在异常处理段中,可以看到有个异常对象,该对象就是内置对象`exception`。
`exception`对象仅在异常处理页面中才有效,通过前面的异常处理结构,读者可以非常清晰地看出这点

## _jspService方法中已经有异常处理代码
打开普通`JSP`页面所生成的`Servlet`类,将可以发现如下代码片段
```java
public void _jspService(final javax.servlet.http.HttpServletRequest request,
        final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {
    ......
    try {
        response.setContentType("text/html; charset=UTF-8");
        ......
        out.write("<!DOCTYPE html>\r\n");
        out.write("<html>\r\n");
        ......
        out.write("</html>");
    } catch (java.lang.Throwable t) {
        if (!(t instanceof javax.servlet.jsp.SkipPageException)) {
            out = _jspx_out;
            if (out != null && out.getBufferSize() != 0)
                try {
                    if (response.isCommitted()) {
                        out.flush();
                    } else {
                        out.clearBuffer();
                    }
                } catch (java.io.IOException e) {
                }
            if (_jspx_page_context != null)
                _jspx_page_context.handlePageException(t);
            else
                throw new ServletException(t);
        }
    } finally {
        _jspxFactory.releasePageContext(_jspx_page_context);
    }
}
```
从上面代码的粗体字代码中可以看出,`JSP`脚本和静态`HTML`部分都将转换成`_jspService`方法里的执行性代码这就是`JSP`脚本无须处理异常的原因:因为这些脚本已经处于`try`块中。一旦`try`块捕捉到`JSP`脚本的异常,并且`_jspx_page_context`不为`null`,就会由该对象来处理该异常。
`_jspx_page_context`对异常的处理也非常简单:如果该页面的`page`指令指定了`errorPage`属性,则将请求`forward`到`errorPage`属性指定的页面,否则使用系统页面来输出异常信息。

由于只有`JSP`脚本、输出表达式才会对应于`_jspService`方法里的代码,所以这两个部分的代码无须处理`checked`异常。但`JSP`的声明部分依然需要处理`checked`异常,**`JSP`的异常处理机制对`JSP`声明不起作用**。
在`JSP`的异常处理机制中,一个异常处理页面可以处理多个`JSP`页面脚本部分的异常。异常处理页面通过`page`指令的`errorPage`属性确定。
## throwEx.jsp
下面的页面再次测试了`JSP`脚本的异常机制。
```jsp
<!-- 通过errorPage属性指定异常处理页面 -->
<%@ page contentType="text/html; charset=UTF-8" language="java" errorPage="error.jsp" %>
<!DOCTYPE html>
<html>
<head>
    <title> JSP脚本的异常机制 </title>
</head>
<body>
<%
int a = 6;
int c = a / 0;
%>
</body>
</html>
```
以上页面的粗体字代码将抛出一个`ArithmeticEception`,则`JSP`异常机制将会转发到`error.jsp`页面.
## error.jsp
`error.jsp`页面代码如下。
<pre>
<%@ page contentType="text/html; charset=UTF-8" language="java" <mark>isErrorPage="true"</mark> %>
<!DOCTYPE html>
<html>
<head>
    <title> 异常处理页面 </title>
</head>
<body>
异常类型是:<%=exception.getClass()%><br/>
异常信息是:<%=exception.getMessage()%><br/>
</body>
</html>
</pre>
以上页面`page`指令的`isErrorPage`属性被设为`true`,则可以通过`exception`对象来访间上一个页面所出现的异常。
## 测试
在浏览器中请求`throwEx.jsp`页面,将看到如图2.22所示的界面
## _jspService方法
打开`error.jsp`页面生成的`Servlet`类,在`_jspService()`方法中发现如下代码片段
<pre>
public void _jspService(final javax.servlet.http.HttpServletRequest request,
        final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable <mark><strong>exception</strong></mark> = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
        response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    ......
}
</pre>
从以上代码片段的粗体字代码中可以看出,当`JSP`页面`page`指令的`isErrorPage`为`true`时,该页面就会提供`exception`内置对象。
## 在异常处理页面才能访问exception内置对象
应将异常处理页面中`page`指令的`isErrorPage`属性设置为`true`。只有当`isErrorPage`属性设置为`true`时才可访问`exception`内置对象.
